version: '3'
services:
  nginx:
    container_name: beadgame_nginx
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
        - "80:80"
    volumes:
      - ./feed-reader:/var/www/html
      - ./conf.d:/etc/nginx/sites-enabled
    links:
      - php
      - db
    depends_on:
      - db
    networks:
      - beadgame
  php:
    container_name: beadgame_php
    build:
      context: ./
      dockerfile: Dockerfile-php
    volumes:
      - ./feed-reader:/var/www/html
    networks:
      - beadgame
  db:
    image: mysql:latest
    container_name: beadgame_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beadgame
    networks:
      - beadgame
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: beadgame_pma
    links:
      - db
    depends_on:
      - db
    ports:
      - "8184:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    networks:
      - beadgame
networks:
  beadgame:
    driver: bridge
